name: bank
services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=bank
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d bank"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/bank?sslmode=disable